version: "3.8"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: kusinsa_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3307
      TZ: Asia/Seoul
    ports:
      - 3307:3307
    expose:
      - 3307
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
